<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <OutputPath>../../artifacts/BridgeTools/TotalFog</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <DebugType>None</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="TotalFog" HintPath="../../1.6/Assemblies/TotalFog.dll" Private="false" />
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4871" ExcludeAssets="runtime" />
    <PackageReference Include="Lib.Harmony.Ref" Version="2.4.2" ExcludeAssets="runtime" />
    <PackageReference Include="RimBridgeServer.Sdk" Version="2.0.0" PrivateAssets="all" ExcludeAssets="runtime" />
  </ItemGroup>
</Project>
